### PR TITLE
Small changes to Calypso for node based sender/implementers (uses  pr on Pharo - 22175)

### PR DESCRIPTION
**Pull request by macta**
NOTE: This PR needs to be based on the PR on pharo: (22175) senders and implementors doesnt properly use the ast and cursor location).

As you can see it's quite trivial - we just need to stop the inherited behavior from Nautilus that selects a line if there is no selection. Instead, we can use the cursor location to figure out what code node you are positioned on, and do something better.

Should be pretty safe as if we hit edge cases, you can still highlight something (like people are used to doing) and it will use the old mechanism.

### CODE REVIEW

**Comment by macta** [comment]
As this PR is now in Pharo - what do I need to do to get this applied so that senders/implementers/references can use proper node based ast searches?

**Comment by dionisiydk** [comment]
Hi, Tim.
Thanks for remind.
It just needs to be merged and released.
Before I was waiting integration of previous version. Now it is done.

вт, 14 авг. 2018 г., 9:10 Tim Mackinnon <notifications@github.com>:

**Comment by macta** [comment]
Cool - thanks. I’ve got a few other similar changes but I’ll need your advice on how to implement keyboard shortcuts in Calypso.

I’m after some single key commands for “widen/extend selection” (In Nautilus i used meta-e) and also “jump to next keyword/token” (meta-j).

I’m trying to get us a bit closer to IntellJ and those are common operations I find for refactoring and also post keyword completion.

**Comment by dionisiydk** [comment]
For general text commands you should annotate them with CmdShortcutActivation for ClyTextEditorContext. 
For example look at SycRenameTempCommand. It uses ClySourceCodeContext. But it is subclass of ClyTextEditorContext. So you should find how to do things.

**Comment by macta** [comment]
I can see those commands and can get most of the way there - however I’m wondering how/if I can locate the cursor position (the best I can see is to get the location of the current node - and I’m wondering what happens if the source is broken in that case) but then if I want to move the cursor or extend the current selection - how can I access this aspect of the text widget?

**Comment by dionisiydk** [comment]
All logic is implemented inside text morph (RubScrolledTextMorph). And it is not simple part.
To access text morph just use message chain:
```Smalltalk
aTextEditorContext tool textMorph
```
And do whatever you want with this guy. 
Then try to introduce proper API for new features. And we can add them directly to context

**Pull request merged**
