### PR TITLE
keepTargetClassesInMethodEditor

### PR DESCRIPTION
**Pull request by dionisiydk**
Now method editors detect and store target classes  during initialization. So they are same in any browser context.
It means that when you switch to another class the dirty method will be compiled in original class. Previously it asked user where to compile using new selected class and original method class

### CODE REVIEW

**Comment by estebanlm** [comment]
again it fails on P7 :( 
this is sad, how can we know change is working good? we need to fix it

**Comment by dionisiydk** [comment]
yes, it is annoying. Now testing is manual loading in fresh image and running all tests.

I look into Iceberg preload CI script. It lists all packages. Do you know how to generate this list by script?
I wonder that there is no baseline unload feature.

**Comment by estebanlm** [comment]
ok, fixed :)

**Comment by dionisiydk** [comment]
thanks @estebanlm

**Pull request merged**
