### PR TITLE
388-ffiCalloutSelectors-should-not-be-hardcoded-in-CompiledMethod--isFFICall

### LINKED ISSUE #388: ffiCalloutSelectors should not be hardcoded in CompiledMethod >> isFFICall
When https://pharo.fogbugz.com/f/cases/22785/Refactor-FFICompilerPlugin is integrated
the method CompiledMethod >> isFFICall should use FFICompilerPlugin(class)>>ffiCalloutSelectors
instead of copying the selectors

Pharo issue

https://pharo.fogbugz.com/f/cases/22787/ffiCalloutSelectors-should-not-be-hardcoded-in-CompiledMethod-isFFICall

### PR DESCRIPTION
**Pull request by jecisc**
Remove #isFFICall and use #isFFIMethod.

Fixes #388

### CODE REVIEW

**Comment by jecisc** [comment]
Apparently, the 6.1 version is still building. In the issue it was written that the support was droped. Is that right?

**Comment by guillep** [comment]
I don't know...

**Comment by dionisiydk** [comment]
@jecisc  There was changes in code editor which are incompatible with Pharo 6. They are not covered by tests.

**Comment by dionisiydk** [comment]
At least it is what I thought about code navigation changes. 
But I don't check Pharo 6 and I can be wrong about it.

**Comment by dionisiydk** [comment]
But CI for Pharo 6 is pretty useful because Calypso loaded from scratch there. It avoids issues with updating code and it allows to check functional changes.

**Comment by jecisc** [comment]
Ok, just tell me what to do about this PR. Anyway, it’s not urgent because it’s not a show stopper for Pharo 7. It can be integrated for P8.

**Comment by dionisiydk** [comment]
I let other guys decide (@estebanlm, @guillep, ..). If we will integrate it now then we should disable Pharo6 CI because it will be always red.

**Comment by jecisc** [comment]
Moved to Pharo: https://github.com/pharo-project/pharo/pull/3848

**Pull request closed without merging**
